matrix:
- name: Markdown
  sources:
    - '**/*.md' 
  expect_match: false   # false -> supress errors if no markdown files were edited
  aspell:
    lang: en
    mode: none
    add-filter:
      - url
    camel-case: true        # accept CamelCase words
    run-together: true 
  dictionary:
    wordlists:
    - .wordlist.txt
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
  default_encoding: utf-8
  suggest: true
