# This is workflow for spell checking using PySpelling lib (https://pypi.org/project/pyspelling/)
name: Spellcheck

on:
  push:
    branches: 
      - ${{ github.ref }}
  pull_request:
    branches: 
      - ${{ github.head_ref }}
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get changed files
        run: |
          echo "CHANGED_FILES=$(gh pr diff ${{ github.event.number }} --name-only | grep '\.md$' | xargs -I {} echo "{}")" >> $GITHUB_ENV
      
      - uses: igsekor/pyspelling-any@v1.0.4
        name: Spellcheck
        env:
          MATRIX: ${{ toJson(env.CHANGED_FILES) }}
          
