name: Spellcheck

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install aspell
        run: sudo apt-get install -y aspell aspell-en

      - name: Run spellcheck
        uses: igsekor/pyspelling-any@v1.0.4
        with:
          args: "-c ./spellcheck.yaml"

