name: Spellcheck(Repo)

on:
  schedule:
    - cron: "0 0 * * 2"   # Every Tuesday
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Spellcheck
        uses: rojopolis/spellcheck-github-actions@v0
        with:
          task_name: Markdown
          config_path: .spellcheck.yml
